### ISSUE TITLE
bin/runsvdir-dyno: 19: exec: runsvdir: not found

### ISSUE THREAD

**Issue by ByrdOfAFeather** [danp/heroku-buildpack-runit#10]
I keep getting this error upon deployment, it seems like the compile bash script isn't called before it runs the runit command. I'm not sure if I've missed something here. 

Procfile: 
web: bin/runsvdir-dyno

Procfile.web:
django: gunicorn path.to.wsgi:application --bind 127.0.0.1:$DJANGO_PORT
node: node server.js

Otherwise, the bin folder is unchanged from this repo.

**Comment by marianopenn-jhu** [comment]
Have you found a solution?

**Comment by aidensgithub** [comment]
> Have you found a solution?

Have you found a solution? No solutions?
