### ISSUE TITLE
Not supported on heroku-22 stack

### ISSUE THREAD

**Issue by cytsai1008** [danp/heroku-buildpack-runit#17]
I don't know why?
I'm using python on heroku
In heroku-20 it work perfectly, but when upgrading into heroku-22 it just broken
Below is my log, hopes it will helps. 🥺
```
Starting process with command `bin/runsvdir-dyno`
heroku[web.1]: State changed from starting to crashed
app[web.1]: /usr/bin/env: ‘ruby’: No such file or directory
heroku[web.1]: Process exited with status 127
```

**Comment by danp** [comment]
Thanks for the note! I see in the [Heroku-22 What's new section](https://devcenter.heroku.com/articles/heroku-22-stack#what-s-new) that it no longer includes a system Ruby installation, which is what this buildpack depends on. I'll try to work around that at some point but not sure when I'll get to it.

**Comment by cytsai1008** [comment]
I've successfully to upgrading to heroku-22 by adding ruby buildpack, Gemfile, and Gemfile.lock to manual install ruby, maybe you can add this to readme? (BTW it require ruby 3.1.0 and later but default version is 3.0.3)
